apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-micrometer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-micrometer
  template:
    metadata:
      labels:
        app: spring-boot-micrometer
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: spring-boot-micrometer-app
          image: john3kuae/spring-boot-micrometer:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseContainerSupport -XX:NativeMemoryTracking=summary -XX:+UnlockExperimentalVMOptions  -XX:+UseCGroupMemoryLimitForHeap -XX:InitialRAMFraction=4 -XX:MaxRAMFraction=1 -XX:+UseG1GC -XX:+UseStringDeduplication -XX:G1ReservePercent=10"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-micrometer
spec:
  selector:
    app: spring-boot-micrometer
  ports:
    - port: 8082
      targetPort: 8080
  type: LoadBalancer